#!/bin/bash

set -e

if [[ "$WIRELESS_SID" != "" ]]; then
    if [[ "$WIRELESS_PASSWORD" != "" ]]; then
        OPTIONAL_PASSWORD="password '$WIRELESS_PASSWORD'"
    fi
    
    OUTPUT=$(eval \
            "nmcli device wifi connect '$WIRELESS_SID' $OPTIONAL_PASSWORD" 2>&1)
    
    if [[ "$?" != "0" ]]; then
        notify-mb-user --urgency normal "Couldn't connect to wireless: $OUTPUT"
        echo -e "$OUTPUT" > "/home/$MEDIA_BOX_USER/wireless.error"
        exit 1
    fi
fi

timeout 15 /bin/bash \
        <<<'until sleep 1 && ping -c1 google.com &> /dev/null; do :; done'

if [[ "$?" != "0" ]]; then
    notify-mb-user --urgency normal "No internet connection."
    exit 1
fi

notify-mb-user "Connected to the internet."
