#!/bin/bash

set -e
set -x

echo Beginning update...

source /mnt/fossil/dandlessy-config

if [[ -f /mnt/fossil/configureConnection ]]; then
    /bin/bash /mnt/fossil/configureConnection
fi

echo -n 'Waiting for internet...'
if nm-online && ! ping -c 1 -w 30 -i 2 8.8.8.8 &> /dev/null; then
    echo '...never found it. :('
    exit 1
fi

echo 'found!'

if [[ ! -L /etc/ssh/ssh_known_hosts ]]; then
    rm /etc/ssh/ssh_known_hosts || true
    mkdir -p /etc/ssh
    ln -s /mnt/fossil/known_hosts /etc/ssh/ssh_known_hosts
fi

source /mnt/fossil/dandlessy-config

cd /root
if [[ ! -d dandlessy ]]; then
    git clone $UPDATE_REPO dandlessy
fi

if [[ "$UPDATE_BRANCH" = "" ]]; then
    UPDATE_BRANCH="master"
fi

cd dandlessy
git reset --hard HEAD
git clean -df
git checkout $UPDATE_BRANCH

git fetch origin
git reset --hard origin/$UPDATE_BRANCH
git clean -df

cd src/update
/bin/bash update.sh

echo Done!
