#!/bin/bash

set -e
set -x

echo Beginning update...

source /mnt/fossil/dandlessy-config

cd /root
if [[ -d dandlessy ]]; then
    git clone $UPDATE_REPO dandlessy
fi

cd dandlessy
git fetch origin
git reset --hard origin/master
git clean -df

cd src/update
/bin/bash update.sh

echo Done!
