#!/bin/bash

# Networking:
# Network config shared between normal and update mode should go in a file at
# root of the fossil partition called `configureConnection`.  It will be called
# at each boot-up and should be appropriately idempotent.

# Autorun when booting into the update partition.
UPDATE_CMD='dandlessy-update'
UPDATE_REPO='https://github.com/hamptonsmith/dandlessy.git'

# Specifies the partition device where installs should be performed.  Probably
# never any good reason to update this.
MAIN_PARTITION={{main-partition}}

# Allows you to change what you initially set during the bootstrap process.
# Won't take effect until update.
HOSTNAME={{hostname}}
MEDIA_BOX_USER={{media-box-user}}

# Variables that match FSTAB_ENTRY_* will be added to /etc/fstab on boot.
#FSTAB_ENTRY_XYZ=...

TORRENT_COMPLETED_DIRECTORY=/home/$MEDIA_BOX_USER/media/completed
TORRENT_FILE_DIRECTORY=/home/$MEDIA_BOX_USER/media/torrent-files
TORRENT_IN_PROGRESS_DIRECTORY=/home/$MEDIA_BOX_USER/media/in-progress
MEDIA_CACHE_DIRECTORY=/home/$MEDIA_BOX_USER/media/cache
MEDIA_VIDEO_DIRECTORY=/home/$MEDIA_BOX_USER/videos

STEAM_LIBRARY_DIRECTORY=/home/$MEDIA_BOX_USER/steam-apps

# Variables that match DANDAPP_* will be added to the app menu.  Format is:
# label;sublabel;bashcommand
DANDAPP_NETFLIX='Netflix;;web-app https://www.netflix.com'

# Get a list with: pacmd list-sinks | grep 'name:'
#PULSE_AUDIO_DEFAULT_SINK=asdf

# Any extra i3 config
#I3_CONFIG_EXTRAS='';
